language: csharp
dist: trusty
notifications:
  email: never
mono: none
dotnet: 1.0.1
before_install:
script:
  - dotnet restore -v Minimal
  - dotnet build src/Slugify.Core/ -c Release -f netstandard1.3
  - dotnet test tests/Slugify.Core.Tests/Slugify.Core.Tests.csproj