notifications:
  email: never
language: csharp
sudo: required
dist: trusty
os:
  - linux
  - osx
osx_image: xcode7.1
mono: 4.0.5
dotnet: 1.0.0-preview2-003131
script:
- dotnet restore -v Minimal
- dotnet build **/project.json -c Release
